#!/usr/bin/env bash
# Install load balancer HAproxy with version 1.5 or greater
apt-get -y update
apt-get install haproxy -y

# Set ENABLED to 1 if you want the init script to start haproxy.
echo "ENABLED=1" >> /etc/default/haproxy

echo -e "\nlisten 124509-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\toption forwardfor\n\tserver 124509-web-01 54.237.51.138 check\n\tserver 124509-web-02 34.229.254.255 check\n" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
